from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3 as sql
from PyQt5.QtWidgets import QMessageBox

class Ui_ProfInfoWindow(object):
    
    def insert_into(self):
        conn = sql.connect("D:\Me\Comp\PYTHON\Project For Poors\Kosar Yaghoobzadeh\INTERFACE\my_db.db")
        c = conn.cursor()
        self.PRID = self.PRID_show.text()
        self.PRNAME = self.PRNAME_show.text()
        self.PRRANK = self.PRRANK_show.text()
        self.PRFROM = self.STLEV_show.text()
        self.PRSTATUS = self.PRSTATUS_show.text()
        
        c.execute("""INSERT INTO tbl_prof
            (PRID, PNAME, PRANK, PFROM, PRSTATE) 
            VALUES (?,?,?,?,?)""", (self.PRID, self.PRNAME, self.PRRANK, self.PRFROM, self.PRSTATUS))
        conn.commit()
        c.close()
        self.popup_error()
    
    def setupPr(self, ProfInfoWindow):
        ProfInfoWindow.setObjectName("ProfInfoWindow")
        ProfInfoWindow.resize(721, 469)
        self.centralwidget = QtWidgets.QWidget(ProfInfoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PRNAME_lable = QtWidgets.QLabel(self.centralwidget)
        self.PRNAME_lable.setGeometry(QtCore.QRect(560, 195, 111, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.PRNAME_lable.setFont(font)
        self.PRNAME_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.PRNAME_lable.setObjectName("PRNAME_lable")
        self.PRRANK_label = QtWidgets.QLabel(self.centralwidget)
        self.PRRANK_label.setGeometry(QtCore.QRect(220, 105, 111, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.PRRANK_label.setFont(font)
        self.PRRANK_label.setAlignment(QtCore.Qt.AlignCenter)
        self.PRRANK_label.setObjectName("PRRANK_label")
        self.STLEV_label = QtWidgets.QLabel(self.centralwidget)
        self.STLEV_label.setGeometry(QtCore.QRect(220, 195, 101, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.STLEV_label.setFont(font)
        self.STLEV_label.setAlignment(QtCore.Qt.AlignCenter)
        self.STLEV_label.setObjectName("STLEV_label")
        self.PRID_label = QtWidgets.QLabel(self.centralwidget)
        self.PRID_label.setGeometry(QtCore.QRect(560, 105, 141, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.PRID_label.setFont(font)
        self.PRID_label.setAlignment(QtCore.Qt.AlignCenter)
        self.PRID_label.setObjectName("PRID_label")
        self.PRSTATUS_label = QtWidgets.QLabel(self.centralwidget)
        self.PRSTATUS_label.setGeometry(QtCore.QRect(570, 285, 111, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.PRSTATUS_label.setFont(font)
        self.PRSTATUS_label.setAlignment(QtCore.Qt.AlignCenter)
        self.PRSTATUS_label.setObjectName("PRSTATUS_label")
        self.PRID_show = QtWidgets.QLineEdit(self.centralwidget)
        self.PRID_show.setGeometry(QtCore.QRect(400, 110, 141, 31))
        self.PRID_show.setObjectName("PRID_show")
        self.STLEV_show = QtWidgets.QLineEdit(self.centralwidget)
        self.STLEV_show.setGeometry(QtCore.QRect(70, 200, 141, 31))
        self.STLEV_show.setObjectName("STLEV_show")
        self.PRNAME_show = QtWidgets.QLineEdit(self.centralwidget)
        self.PRNAME_show.setGeometry(QtCore.QRect(400, 200, 141, 31))
        self.PRNAME_show.setObjectName("PRNAME_show")
        self.PRRANK_show = QtWidgets.QLineEdit(self.centralwidget)
        self.PRRANK_show.setGeometry(QtCore.QRect(70, 110, 141, 31))
        self.PRRANK_show.setObjectName("PRRANK_show")
        self.PRSTATUS_show = QtWidgets.QLineEdit(self.centralwidget)
        self.PRSTATUS_show.setGeometry(QtCore.QRect(400, 290, 141, 31))
        self.PRSTATUS_show.setObjectName("PRSTATUS_show")
        self.SubmitButton = QtWidgets.QPushButton(self.centralwidget)
        self.SubmitButton.setGeometry(QtCore.QRect(320, 350, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SubmitButton.setFont(font)
        self.SubmitButton.setObjectName("SubmitButton")
        self.SubmitButton.clicked.connect(self.insert_into)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        ProfInfoWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ProfInfoWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 721, 26))
        self.menubar.setObjectName("menubar")
        ProfInfoWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ProfInfoWindow)
        self.statusbar.setObjectName("statusbar")
        ProfInfoWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ProfInfoWindow)
        QtCore.QMetaObject.connectSlotsByName(ProfInfoWindow)

    def retranslateUi(self, ProfInfoWindow):
        _translate = QtCore.QCoreApplication.translate
        ProfInfoWindow.setWindowTitle(_translate("ProfInfoWindow", "Prof info"))
        self.PRNAME_lable.setText(_translate("ProfInfoWindow", ":Name"))
        self.PRRANK_label.setText(_translate("ProfInfoWindow", ":Rank"))
        self.STLEV_label.setText(_translate("ProfInfoWindow", ":From"))
        self.PRID_label.setText(_translate("ProfInfoWindow", ":Pr Id"))
        self.PRSTATUS_label.setText(_translate("ProfInfoWindow", ":Status"))
        self.SubmitButton.setText(_translate("ProfInfoWindow", "submit"))
        self.label.setText(_translate("ProfInfoWindow", "New Professor"))

    def popup_error(self):
        msg = QMessageBox()
        msg.setWindowTitle("Extended")
        msg.setText("New Professor added")
        msg.setIcon(QMessageBox.Warning)
        msg.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProfInfoWindow = QtWidgets.QMainWindow()
    ui = Ui_ProfInfoWindow()
    ui.setupPr(ProfInfoWindow)
    ProfInfoWindow.show()
    sys.exit(app.exec_())
