from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3 as sql
from PyQt5.QtWidgets import QMessageBox

class Ui_StInfoWindow(object):
    
    def insert_into(self):
        conn = sql.connect("D:\Me\Comp\PYTHON\Project For Poors\Kosar Yaghoobzadeh\INTERFACE\my_db.db")
        c = conn.cursor()
        self.STID = self.StNumEdit.text()
        self.STNAME = self.StNameEdit.text()
        self.STLEV = self.StLevEdit.text()
        self.STMJR = self.StMjrEdit.text()
        self.STAGE = self.StAgeEdit.text()
        self.STSTATUS = self.StStatusEdit.text()
        c.execute("""INSERT INTO tbl_stt
            (STID, STNAME, STLEV, STMJR, AGE, STSTATE) 
            VALUES (?,?,?,?,?,?)""", (self.STID, self.STNAME, self.STLEV, self.STMJR, self.STAGE, self.STSTATUS))
        conn.commit()
        c.close()
        self.popup_error()
        
    def setupStInfo(self, StInfoWindow):
        StInfoWindow.setObjectName("StInfoWindow")
        StInfoWindow.resize(721, 469)
        self.centralwidget = QtWidgets.QWidget(StInfoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.StName_label = QtWidgets.QLabel(self.centralwidget)
        self.StName_label.setGeometry(QtCore.QRect(560, 195, 111, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.StName_label.setFont(font)
        self.StName_label.setAlignment(QtCore.Qt.AlignCenter)
        self.StName_label.setObjectName("StName_label")
        self.StAge_label = QtWidgets.QLabel(self.centralwidget)
        self.StAge_label.setGeometry(QtCore.QRect(560, 285, 51, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.StAge_label.setFont(font)
        self.StAge_label.setAlignment(QtCore.Qt.AlignCenter)
        self.StAge_label.setObjectName("StAge_label")
        self.StMjr_label = QtWidgets.QLabel(self.centralwidget)
        self.StMjr_label.setGeometry(QtCore.QRect(220, 105, 111, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.StMjr_label.setFont(font)
        self.StMjr_label.setAlignment(QtCore.Qt.AlignCenter)
        self.StMjr_label.setObjectName("StMjr_label")
        self.StLev_label = QtWidgets.QLabel(self.centralwidget)
        self.StLev_label.setGeometry(QtCore.QRect(230, 195, 101, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.StLev_label.setFont(font)
        self.StLev_label.setAlignment(QtCore.Qt.AlignCenter)
        self.StLev_label.setObjectName("StLev_label")
        self.StNum_label = QtWidgets.QLabel(self.centralwidget)
        self.StNum_label.setGeometry(QtCore.QRect(560, 105, 141, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.StNum_label.setFont(font)
        self.StNum_label.setAlignment(QtCore.Qt.AlignCenter)
        self.StNum_label.setObjectName("StNum_label")
        self.StStatus_label = QtWidgets.QLabel(self.centralwidget)
        self.StStatus_label.setGeometry(QtCore.QRect(230, 285, 111, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.StStatus_label.setFont(font)
        self.StStatus_label.setAlignment(QtCore.Qt.AlignCenter)
        self.StStatus_label.setObjectName("StStatus_label")
        # --------------------------------------------------------
        # --------------------------------------------------------
        # --------------------------------------------------------
        self.StNumEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.StNumEdit.setGeometry(QtCore.QRect(400, 110, 141, 31))
        self.StNumEdit.setObjectName("StNumEdit")
        self.StAgeEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.StAgeEdit.setGeometry(QtCore.QRect(400, 290, 141, 31))
        self.StAgeEdit.setObjectName("StAgeEdit")
        self.StLevEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.StLevEdit.setGeometry(QtCore.QRect(70, 200, 141, 31))
        self.StLevEdit.setObjectName("StLevEdit")
        self.StNameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.StNameEdit.setGeometry(QtCore.QRect(400, 200, 141, 31))
        self.StNameEdit.setObjectName("StNameEdit")
        self.StMjrEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.StMjrEdit.setGeometry(QtCore.QRect(70, 110, 141, 31))
        self.StMjrEdit.setObjectName("StMjrEdit")
        self.StStatusEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.StStatusEdit.setGeometry(QtCore.QRect(70, 290, 141, 31))
        self.StStatusEdit.setObjectName("StStatusEdit")
        # --------------------------------------------------
        # --------------------------------------------------
        # --------------------------------------------------
        self.SubmitButton = QtWidgets.QPushButton(self.centralwidget)
        self.SubmitButton.setGeometry(QtCore.QRect(320, 350, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SubmitButton.setFont(font)
        self.SubmitButton.setObjectName("SubmitButton")
        self.SubmitButton.clicked.connect(self.insert_into)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 30, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        StInfoWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StInfoWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 721, 26))
        self.menubar.setObjectName("menubar")
        StInfoWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StInfoWindow)
        self.statusbar.setObjectName("statusbar")
        StInfoWindow.setStatusBar(self.statusbar)

        self.retranslateUi(StInfoWindow)
        QtCore.QMetaObject.connectSlotsByName(StInfoWindow)

    def retranslateUi(self, StInfoWindow):
        _translate = QtCore.QCoreApplication.translate
        StInfoWindow.setWindowTitle(_translate("StInfoWindow", "Student Info"))
        self.StName_label.setText(_translate("StInfoWindow", ":St Name"))
        self.StAge_label.setText(_translate("StInfoWindow", ":Age"))
        self.StMjr_label.setText(_translate("StInfoWindow", ":Major"))
        self.StLev_label.setText(_translate("StInfoWindow", ":Level"))
        self.StNum_label.setText(_translate("StInfoWindow", ":St ID"))
        self.StStatus_label.setText(_translate("StInfoWindow", ":Still Edu"))
        self.SubmitButton.setText(_translate("StInfoWindow", "submit"))
        self.label.setText(_translate("StInfoWindow", "New Student"))

    def popup_error(self):
        msg = QMessageBox()
        msg.setWindowTitle("Extended")
        msg.setText("A new Student added!")
        msg.setIcon(QMessageBox.Warning)
        msg.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StInfoWindow = QtWidgets.QMainWindow()
    ui = Ui_StInfoWindow()
    ui.setupStInfo(StInfoWindow)
    StInfoWindow.show()
    sys.exit(app.exec_())
