from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3 as sql
from PyQt5.QtWidgets import QMessageBox

class Ui_PRInfo(object):
    def __init__(self, row):
        self.PRID = row[0]
        self.PRNAME = row[1]
        self.PRLEV = row[2]
        self.AGE = row[3]
        self.STATUS = row[4]
    
    def Delete_ST(self):
        conn = sql.connect("DataBase Address in your PC")
        c = conn.cursor()
        c.execute("DELETE FROM tbl_prof WHERE PRID='{}'".format(self.PRID))
        conn.commit()
        c.close()
        self.popup_error()
    
    def setupPrinfo(self, PRInfo):
        PRInfo.setObjectName("PRInfo")
        PRInfo.resize(847, 469)
        self.centralwidget = QtWidgets.QWidget(PRInfo)
        self.centralwidget.setObjectName("centralwidget")
        self.PRName_label = QtWidgets.QLabel(self.centralwidget)
        self.PRName_label.setGeometry(QtCore.QRect(560, 190, 111, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.PRName_label.setFont(font)
        self.PRName_label.setAlignment(QtCore.Qt.AlignCenter)
        self.PRName_label.setObjectName("PRName_label")
        self.PRAge_label = QtWidgets.QLabel(self.centralwidget)
        self.PRAge_label.setGeometry(QtCore.QRect(560, 280, 111, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.PRAge_label.setFont(font)
        self.PRAge_label.setAlignment(QtCore.Qt.AlignCenter)
        self.PRAge_label.setObjectName("PRAge_label")
        self.PRLEV_label = QtWidgets.QLabel(self.centralwidget)
        self.PRLEV_label.setGeometry(QtCore.QRect(220, 100, 111, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.PRLEV_label.setFont(font)
        self.PRLEV_label.setAlignment(QtCore.Qt.AlignCenter)
        self.PRLEV_label.setObjectName("PRLEV_label")
        self.PRID_label = QtWidgets.QLabel(self.centralwidget)
        self.PRID_label.setGeometry(QtCore.QRect(550, 100, 131, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.PRID_label.setFont(font)
        self.PRID_label.setAlignment(QtCore.Qt.AlignCenter)
        self.PRID_label.setObjectName("PRID_label")
        self.PRStatus_label = QtWidgets.QLabel(self.centralwidget)
        self.PRStatus_label.setGeometry(QtCore.QRect(220, 190, 111, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.PRStatus_label.setFont(font)
        self.PRStatus_label.setAlignment(QtCore.Qt.AlignCenter)
        self.PRStatus_label.setObjectName("PRStatus_label")
        self.PRAge_show = QtWidgets.QLabel(self.centralwidget)
        self.PRAge_show.setGeometry(QtCore.QRect(400, 280, 141, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.PRAge_show.setFont(font)
        self.PRAge_show.setText(self.AGE)
        self.PRAge_show.setAlignment(QtCore.Qt.AlignCenter)
        self.PRAge_show.setObjectName("PRAge_show")
        self.PRName_show = QtWidgets.QLabel(self.centralwidget)
        self.PRName_show.setGeometry(QtCore.QRect(400, 190, 141, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.PRName_show.setFont(font)
        self.PRName_show.setText(self.PRNAME)
        self.PRName_show.setAlignment(QtCore.Qt.AlignCenter)
        self.PRName_show.setObjectName("PRName_show")
        self.PRID_show = QtWidgets.QLabel(self.centralwidget)
        self.PRID_show.setGeometry(QtCore.QRect(400, 100, 141, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.PRID_show.setFont(font)
        self.PRID_show.setText(self.PRID)
        self.PRID_show.setAlignment(QtCore.Qt.AlignCenter)
        self.PRID_show.setObjectName("PRID_show")
        self.StStatus_show = QtWidgets.QLabel(self.centralwidget)
        self.StStatus_show.setGeometry(QtCore.QRect(60, 280, 141, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.StStatus_show.setFont(font)
        self.StStatus_show.setText("")
        self.StStatus_show.setAlignment(QtCore.Qt.AlignCenter)
        self.StStatus_show.setObjectName("StStatus_show")
        self.PRLev_show = QtWidgets.QLabel(self.centralwidget)
        self.PRLev_show.setGeometry(QtCore.QRect(60, 190, 141, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.PRLev_show.setFont(font)
        self.PRLev_show.setText(self.STATUS)
        self.PRLev_show.setAlignment(QtCore.Qt.AlignCenter)
        self.PRLev_show.setObjectName("PRLev_show")
        self.PRLEV_SHOW = QtWidgets.QLabel(self.centralwidget)
        self.PRLEV_SHOW.setGeometry(QtCore.QRect(60, 100, 141, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.PRLEV_SHOW.setFont(font)
        self.PRLEV_SHOW.setText(self.PRLEV)
        self.PRLEV_SHOW.setAlignment(QtCore.Qt.AlignCenter)
        self.PRLEV_SHOW.setObjectName("PRLEV_SHOW")
        self.StNum_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.StNum_label_3.setGeometry(QtCore.QRect(370, 30, 171, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.StNum_label_3.setFont(font)
        self.StNum_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.StNum_label_3.setObjectName("StNum_label_3")
        self.SubmitButton = QtWidgets.QPushButton(self.centralwidget)
        self.SubmitButton.setGeometry(QtCore.QRect(390, 340, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SubmitButton.setFont(font)
        self.SubmitButton.setObjectName("SubmitButton")
        self.SubmitButton.clicked.connect(self.Delete_ST)
        self.StAge_show = QtWidgets.QLabel(self.centralwidget)
        PRInfo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PRInfo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 847, 26))
        self.menubar.setObjectName("menubar")
        PRInfo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PRInfo)
        self.statusbar.setObjectName("statusbar")
        PRInfo.setStatusBar(self.statusbar)

        self.retranslateUi(PRInfo)
        QtCore.QMetaObject.connectSlotsByName(PRInfo)

    def retranslateUi(self, PRInfo):
        _translate = QtCore.QCoreApplication.translate
        PRInfo.setWindowTitle(_translate("PRInfo", "Prof Info"))
        self.PRName_label.setText(_translate("PRInfo", ":Name"))
        self.PRAge_label.setText(_translate("PRInfo", ":From"))
        self.PRLEV_label.setText(_translate("PRInfo", ":Rank"))
        self.PRID_label.setText(_translate("PRInfo", ":Pr ID"))
        self.PRStatus_label.setText(_translate("PRInfo", ":Status"))
        self.StNum_label_3.setText(_translate("PRInfo", "Prof Info"))
        self.SubmitButton.setText(_translate("StInfoWindowNotNew", "Delete Prof"))
        
    def popup_error(self):
        msg = QMessageBox()
        msg.setWindowTitle("Done")
        msg.setText("Professor Deleted")
        msg.setIcon(QMessageBox.Warning)
        msg.exec_()
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PRInfo = QtWidgets.QMainWindow()
    ui = Ui_PRInfo()
    ui.setupPrinfo(PRInfo)
    PRInfo.show()
    sys.exit(app.exec_())
