from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StInfoEdit(object):

        
    def setupEdit(self, StInfoEdit):
        StInfoEdit.setObjectName("StInfoEdit")
        StInfoEdit.resize(847, 469)
        self.centralwidget = QtWidgets.QWidget(StInfoEdit)
        self.centralwidget.setObjectName("centralwidget")
        self.StName_label = QtWidgets.QLabel(self.centralwidget)
        self.StName_label.setGeometry(QtCore.QRect(560, 190, 111, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.StName_label.setFont(font)
        self.StName_label.setAlignment(QtCore.Qt.AlignCenter)
        self.StName_label.setObjectName("StName_label")
        self.StAge_label = QtWidgets.QLabel(self.centralwidget)
        self.StAge_label.setGeometry(QtCore.QRect(560, 280, 51, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.StAge_label.setFont(font)
        self.StAge_label.setAlignment(QtCore.Qt.AlignCenter)
        self.StAge_label.setObjectName("StAge_label")
        self.StMjr_label = QtWidgets.QLabel(self.centralwidget)
        self.StMjr_label.setGeometry(QtCore.QRect(220, 100, 111, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.StMjr_label.setFont(font)
        self.StMjr_label.setAlignment(QtCore.Qt.AlignCenter)
        self.StMjr_label.setObjectName("StMjr_label")
        self.StLev_label = QtWidgets.QLabel(self.centralwidget)
        self.StLev_label.setGeometry(QtCore.QRect(230, 190, 101, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.StLev_label.setFont(font)
        self.StLev_label.setAlignment(QtCore.Qt.AlignCenter)
        self.StLev_label.setObjectName("StLev_label")
        self.StNum_label = QtWidgets.QLabel(self.centralwidget)
        self.StNum_label.setGeometry(QtCore.QRect(560, 100, 141, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.StNum_label.setFont(font)
        self.StNum_label.setAlignment(QtCore.Qt.AlignCenter)
        self.StNum_label.setObjectName("StNum_label")
        self.StStatus_label = QtWidgets.QLabel(self.centralwidget)
        self.StStatus_label.setGeometry(QtCore.QRect(230, 280, 111, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(13)
        self.StStatus_label.setFont(font)
        self.StStatus_label.setAlignment(QtCore.Qt.AlignCenter)
        self.StStatus_label.setObjectName("StStatus_label")
        self.StNum_show = QtWidgets.QLabel(self.centralwidget)
        self.StNum_show.setGeometry(QtCore.QRect(400, 100, 151, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(10)
        self.StNum_show.setFont(font)
        self.StNum_show.setText("")
        self.StNum_show.setAlignment(QtCore.Qt.AlignCenter)
        self.StNum_show.setObjectName("StNum_show")
        self.StNum_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.StNum_label_3.setGeometry(QtCore.QRect(280, 30, 261, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.StNum_label_3.setFont(font)
        self.StNum_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.StNum_label_3.setObjectName("StNum_label_3")
        self.StNameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.StNameEdit.setGeometry(QtCore.QRect(400, 200, 141, 31))
        self.StNameEdit.setText("")
        self.StNameEdit.setObjectName("StNameEdit")
        self.StAgeEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.StAgeEdit.setGeometry(QtCore.QRect(400, 290, 141, 31))
        self.StAgeEdit.setText("")
        self.StAgeEdit.setObjectName("StAgeEdit")
        self.StLevEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.StLevEdit.setGeometry(QtCore.QRect(60, 200, 141, 31))
        self.StLevEdit.setText("")
        self.StLevEdit.setObjectName("StLevEdit")
        self.StMjrEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.StMjrEdit.setGeometry(QtCore.QRect(60, 110, 141, 31))
        self.StMjrEdit.setText("")
        self.StMjrEdit.setObjectName("StMjrEdit")
        self.StStatusEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.StStatusEdit.setGeometry(QtCore.QRect(60, 290, 141, 31))
        self.StStatusEdit.setText("")
        self.StStatusEdit.setObjectName("StStatusEdit")
        self.SubmitButton = QtWidgets.QPushButton(self.centralwidget)
        self.SubmitButton.setGeometry(QtCore.QRect(320, 340, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SubmitButton.setFont(font)
        self.SubmitButton.setObjectName("SubmitButton")
        StInfoEdit.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StInfoEdit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 847, 26))
        self.menubar.setObjectName("menubar")
        StInfoEdit.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StInfoEdit)
        self.statusbar.setObjectName("statusbar")
        StInfoEdit.setStatusBar(self.statusbar)

        self.retranslateUi(StInfoEdit)
        QtCore.QMetaObject.connectSlotsByName(StInfoEdit)

    def retranslateUi(self, StInfoEdit):
        _translate = QtCore.QCoreApplication.translate
        StInfoEdit.setWindowTitle(_translate("StInfoEdit", "Student Info Edit"))
        self.StName_label.setText(_translate("StInfoEdit", "نام خانوادگی:"))
        self.StAge_label.setText(_translate("StInfoEdit", "سن:"))
        self.StMjr_label.setText(_translate("StInfoEdit", "رشته تحصیلی:"))
        self.StLev_label.setText(_translate("StInfoEdit", "مقطع تحصیلی:"))
        self.StNum_label.setText(_translate("StInfoEdit", "شماره دانشجویی:"))
        self.StStatus_label.setText(_translate("StInfoEdit", "وضعیت تحصیل:"))
        self.StNum_label_3.setText(_translate("StInfoEdit", "ویراش اطلاعات دانشجو"))
        self.SubmitButton.setText(_translate("StInfoEdit", "تایید"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StInfoEdit = QtWidgets.QMainWindow()
    ui = Ui_StInfoEdit()
    ui.setupEdit(StInfoEdit)
    StInfoEdit.show()
    sys.exit(app.exec_())
